# During build and run, set environment DOMAIN pointing
# to publicly accessible domain where app will be hosted
services:
  app:
    image: local/reflex-app
    build:
      context: .
      args:
        API_URL: https://${DOMAIN:-localhost}
    depends_on:
      - db

  webserver:
    environment:
      DOMAIN: ${DOMAIN:-localhost}
    ports:
      - 443:443
      - 80:80  # for acme-challenge via HTTP
    build:
      context: .
      dockerfile: Caddy.Dockerfile
    depends_on:
      - app

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  db:
    driver: local