[tool.poetry]
name = "tutr-reflex"
version = "0.1.0"
description = ""
authors = ["Evan Harley <evan.harley21@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
reflex = "^0.3.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
